/**
 * CASL Subjects - Shared between frontend and backend
 *
 * These are the nouns that define what resources can be acted upon.
 * Convention: PascalCase for entities, lowercase for modules
 */

// Subjects can be:
// 1. Module names (lowercase) - for module-level access
// 2. Entity names (PascalCase) - for entity-level CRUD

export const Subjects = {
  // Meta
  ALL: 'all', // Superuser - can act on anything

  // Modules (match menu items / feature areas)
  DASHBOARD: 'dashboard',
  CLIENTS: 'clients',
  CREDITS: 'credits',
  EPARGNES: 'epargnes',
  COMPTES: 'comptes',
  TONTINES: 'tontines',
  CAISSE: 'caisse',
  COFFRE: 'coffre',
  COMPTABILITE: 'comptabilite',
  RAPPORTS: 'rapports',
  RH: 'rh',
  ADMIN: 'admin',
  RBAC: 'rbac',
  TERRAIN: 'terrain',
  SETTINGS: 'settings',
  MAINTENANCE: 'maintenance',
  LOYALTY: 'loyalty',
  REGULARISATION: 'regularisation',
  TREASURY: 'treasury',
  ACCOUNTING: 'accounting',
  BOURSE: 'bourse',
  LOGE: 'loge',

  // Entities (for granular resource-level checks)
  USER: 'User',
  CLIENT: 'Client',
  CREDIT: 'Credit',
  DEMANDE_CREDIT: 'DemandeCredit',
  ECHEANCE: 'Echeance',
  COMPTE: 'Compte',
  COMPTE_EPARGNE: 'CompteEpargne',
  COMPTE_COURANT: 'CompteCourant',
  COMPTE_BLOQUE: 'CompteBloque',
  TONTINE: 'Tontine',
  TONTINE_MEMBRE: 'TontineMembre',
  TONTINE_CONTRIBUTION: 'TontineContribution',
  CAISSE_SESSION: 'CaisseSession',
  CAISSE_OPERATION: 'CaisseOperation',
  CAISSE_AGENT: 'CaisseAgent',
  COFFRE_TRANSFERT: 'CoffreTransfert',
  ECRITURE_COMPTABLE: 'EcritureComptable',
  JOURNAL: 'Journal',
  AGENCE: 'Agence',
  EMPLOYE: 'Employe',
  AGENT_TERRAIN: 'AgentTerrain',
  OPERATION_TERRAIN: 'OperationTerrain',
  REEVALUATION: 'Reevaluation',
  NOTIFICATION: 'Notification',
  AUDIT_LOG: 'AuditLog',
  SESSION: 'Session',
  ROLE: 'Role',
  PERMISSION: 'Permission',
  DEPARTMENT: 'Department',
  JOB_POSITION: 'JobPosition',
  PLAN_CREDIT: 'PlanCredit',
  REMBOURSEMENT: 'Remboursement',
  ZONE: 'Zone',
  OBJECTIF: 'Objectif',
  POS_DEVICE: 'PosDevice',
  PROSPECTION: 'Prospection',
  PAIEMENT_TERRAIN: 'PaiementTerrain',
  HORAIRE: 'Horaire',
  PAIE: 'Paie',
  DECLARATION_TVA: 'DeclarationTVA',
  INVOICE: 'Invoice',

  // HR Module Entities
  CONGE: 'Conge',
  FORMATION: 'Formation',
  SANCTION: 'Sanction',
  AVANTAGE: 'Avantage',
  CANDIDATURE: 'Candidature',
  BULLETIN_PAIE: 'BulletinPaie',
  LEAVE_BALANCE: 'LeaveBalance',
  HR_AUDIT: 'HrAudit',

  // Terrain Module Entities
  VISITE: 'Visite',
  INCIDENT: 'Incident',
  PROSPECTION_PRIME: 'ProspectionPrime',
  ARRONDISSEMENT: 'Arrondissement',
  MARCHE: 'Marche',
  PROSPECTION_CONFIG: 'ProspectionConfig',

  // Communication Module Entities
  COMMUNICATION: 'Communication',
  MESSAGE: 'Message',

  // Transfer Module Entities
  TRANSFERT: 'Transfert',
  VIREMENT: 'Virement',

  // Financial Aliases
  ECRITURE: 'Ecriture',
  EPARGNE: 'Epargne',
  SYSTEM: 'system',
} as const;

export type Subject = (typeof Subjects)[keyof typeof Subjects];

// List of all subjects for validation
export const ALL_SUBJECTS = Object.values(Subjects);

// Module subjects only (for menu/route checks)
export const MODULE_SUBJECTS = [
  Subjects.DASHBOARD,
  Subjects.CLIENTS,
  Subjects.CREDITS,
  Subjects.EPARGNES,
  Subjects.COMPTES,
  Subjects.TONTINES,
  Subjects.CAISSE,
  Subjects.COFFRE,
  Subjects.COMPTABILITE,
  Subjects.RAPPORTS,
  Subjects.RH,
  Subjects.ADMIN,
  Subjects.RBAC,
  Subjects.TERRAIN,
  Subjects.SETTINGS,
  Subjects.MAINTENANCE,
  Subjects.LOYALTY,
  Subjects.REGULARISATION,
  Subjects.TREASURY,
  Subjects.ACCOUNTING,
  Subjects.BOURSE,
  Subjects.LOGE,
] as const;

// Entity subjects only (for CRUD operations)
export const ENTITY_SUBJECTS = [
  Subjects.USER,
  Subjects.CLIENT,
  Subjects.CREDIT,
  Subjects.DEMANDE_CREDIT,
  Subjects.ECHEANCE,
  Subjects.COMPTE,
  Subjects.COMPTE_EPARGNE,
  Subjects.COMPTE_COURANT,
  Subjects.COMPTE_BLOQUE,
  Subjects.TONTINE,
  Subjects.TONTINE_MEMBRE,
  Subjects.TONTINE_CONTRIBUTION,
  Subjects.CAISSE_SESSION,
  Subjects.CAISSE_OPERATION,
  Subjects.CAISSE_AGENT,
  Subjects.COFFRE_TRANSFERT,
  Subjects.ECRITURE_COMPTABLE,
  Subjects.JOURNAL,
  Subjects.AGENCE,
  Subjects.EMPLOYE,
  Subjects.AGENT_TERRAIN,
  Subjects.OPERATION_TERRAIN,
  Subjects.REEVALUATION,
  Subjects.NOTIFICATION,
  Subjects.AUDIT_LOG,
  Subjects.SESSION,
  Subjects.ROLE,
  Subjects.PERMISSION,
  Subjects.DEPARTMENT,
  Subjects.JOB_POSITION,
  Subjects.PLAN_CREDIT,
  Subjects.REMBOURSEMENT,
  Subjects.ZONE,
  Subjects.OBJECTIF,
  Subjects.POS_DEVICE,
  Subjects.PROSPECTION,
  Subjects.PAIEMENT_TERRAIN,
  Subjects.HORAIRE,
  Subjects.PAIE,
  Subjects.DECLARATION_TVA,
  Subjects.INVOICE,
  Subjects.PROSPECTION_PRIME,
  Subjects.ARRONDISSEMENT,
  Subjects.MARCHE,
  Subjects.PROSPECTION_CONFIG,
] as const;

// Human-readable labels for UI
export const SUBJECT_LABELS: Record<Subject, string> = {
  [Subjects.ALL]: 'Tout',
  [Subjects.DASHBOARD]: 'Tableau de bord',
  [Subjects.CLIENTS]: 'Clients',
  [Subjects.CREDITS]: 'Crédits',
  [Subjects.EPARGNES]: 'Épargnes',
  [Subjects.COMPTES]: 'Comptes',
  [Subjects.TONTINES]: 'Tontines',
  [Subjects.CAISSE]: 'Caisse',
  [Subjects.COFFRE]: 'Coffre-Fort',
  [Subjects.COMPTABILITE]: 'Comptabilité',
  [Subjects.RAPPORTS]: 'Rapports',
  [Subjects.RH]: 'Ressources Humaines',
  [Subjects.ADMIN]: 'Administration',
  [Subjects.RBAC]: 'Gestion des accès',
  [Subjects.TERRAIN]: 'Agents Terrain',
  [Subjects.USER]: 'Utilisateur',
  [Subjects.CLIENT]: 'Client',
  [Subjects.CREDIT]: 'Crédit',
  [Subjects.DEMANDE_CREDIT]: 'Demande de crédit',
  [Subjects.ECHEANCE]: 'Échéance',
  [Subjects.COMPTE]: 'Compte',
  [Subjects.COMPTE_EPARGNE]: 'Compte épargne',
  [Subjects.COMPTE_COURANT]: 'Compte courant',
  [Subjects.COMPTE_BLOQUE]: 'Compte bloqué',
  [Subjects.TONTINE]: 'Tontine',
  [Subjects.TONTINE_MEMBRE]: 'Membre tontine',
  [Subjects.TONTINE_CONTRIBUTION]: 'Contribution tontine',
  [Subjects.CAISSE_SESSION]: 'Session caisse',
  [Subjects.CAISSE_OPERATION]: 'Opération caisse',
  [Subjects.CAISSE_AGENT]: 'Caisse agent',
  [Subjects.COFFRE_TRANSFERT]: 'Transfert coffre',
  [Subjects.ECRITURE_COMPTABLE]: 'Écriture comptable',
  [Subjects.JOURNAL]: 'Journal comptable',
  [Subjects.AGENCE]: 'Agence',
  [Subjects.EMPLOYE]: 'Employé',
  [Subjects.AGENT_TERRAIN]: 'Agent terrain',
  [Subjects.OPERATION_TERRAIN]: 'Opération terrain',
  [Subjects.REEVALUATION]: 'Réévaluation',
  [Subjects.NOTIFICATION]: 'Notification',
  [Subjects.AUDIT_LOG]: 'Journal d\'audit',
  [Subjects.SESSION]: 'Session',
  [Subjects.ROLE]: 'Rôle',
  [Subjects.PERMISSION]: 'Permission',
  [Subjects.DEPARTMENT]: 'Département',
  [Subjects.JOB_POSITION]: 'Poste',
  [Subjects.PLAN_CREDIT]: 'Plan de crédit',
  [Subjects.REMBOURSEMENT]: 'Remboursement',
  [Subjects.ZONE]: 'Zone',
  [Subjects.OBJECTIF]: 'Objectif',
  [Subjects.POS_DEVICE]: 'Terminal POS',
  [Subjects.PROSPECTION]: 'Prospection',
  [Subjects.PAIEMENT_TERRAIN]: 'Paiement terrain',
  [Subjects.HORAIRE]: 'Horaire',
  [Subjects.PAIE]: 'Paie',
  [Subjects.DECLARATION_TVA]: 'Déclaration TVA',
  [Subjects.INVOICE]: 'Facture',
  [Subjects.SETTINGS]: 'Paramètres',
  [Subjects.MAINTENANCE]: 'Maintenance',
  [Subjects.LOYALTY]: 'Fidélité',
  [Subjects.REGULARISATION]: 'Régularisation',
  // HR Module Entities
  [Subjects.CONGE]: 'Congé',
  [Subjects.FORMATION]: 'Formation',
  [Subjects.SANCTION]: 'Sanction',
  [Subjects.AVANTAGE]: 'Avantage',
  [Subjects.CANDIDATURE]: 'Candidature',
  [Subjects.BULLETIN_PAIE]: 'Bulletin de paie',
  [Subjects.LEAVE_BALANCE]: 'Solde congés',
  [Subjects.HR_AUDIT]: 'Audit RH',
  // Terrain Module Entities
  [Subjects.VISITE]: 'Visite',
  [Subjects.INCIDENT]: 'Incident',
  [Subjects.PROSPECTION_PRIME]: 'Prime de prospection',
  [Subjects.ARRONDISSEMENT]: 'Arrondissement',
  [Subjects.MARCHE]: 'Marché',
  [Subjects.PROSPECTION_CONFIG]: 'Configuration prospection',
  // Communication Module Entities
  [Subjects.COMMUNICATION]: 'Communication',
  [Subjects.MESSAGE]: 'Message',
  // Transfer Module Entities
  [Subjects.TRANSFERT]: 'Transfert',
  [Subjects.VIREMENT]: 'Virement',
  // Financial Entities
  [Subjects.ECRITURE]: 'Écriture',
  [Subjects.EPARGNE]: 'Épargne',
  // Treasury Module
  [Subjects.TREASURY]: 'Trésorerie',
  [Subjects.ACCOUNTING]: 'Comptabilité GL',
  [Subjects.SYSTEM]: 'Système',
  [Subjects.BOURSE]: 'Portefeuille Boursier',
  [Subjects.LOGE]: 'Stockage Documents',
};

// Module to Entity mapping (which entities belong to which module)
export const MODULE_ENTITY_MAP: Record<string, Subject[]> = {
  [Subjects.CLIENTS]: [Subjects.CLIENT],
  [Subjects.CREDITS]: [Subjects.CREDIT, Subjects.DEMANDE_CREDIT, Subjects.ECHEANCE, Subjects.REEVALUATION],
  [Subjects.EPARGNES]: [Subjects.COMPTE_EPARGNE],
  [Subjects.COMPTES]: [Subjects.COMPTE, Subjects.COMPTE_COURANT, Subjects.COMPTE_BLOQUE],
  [Subjects.TONTINES]: [Subjects.TONTINE, Subjects.TONTINE_MEMBRE, Subjects.TONTINE_CONTRIBUTION],
  [Subjects.CAISSE]: [Subjects.CAISSE_SESSION, Subjects.CAISSE_OPERATION, Subjects.CAISSE_AGENT],
  [Subjects.COFFRE]: [Subjects.COFFRE_TRANSFERT],
  [Subjects.COMPTABILITE]: [Subjects.ECRITURE_COMPTABLE, Subjects.JOURNAL],
  [Subjects.RH]: [
    Subjects.EMPLOYE,
    Subjects.CONGE,
    Subjects.FORMATION,
    Subjects.SANCTION,
    Subjects.AVANTAGE,
    Subjects.CANDIDATURE,
    Subjects.PAIE,
    Subjects.BULLETIN_PAIE,
    Subjects.HORAIRE,
    Subjects.LEAVE_BALANCE,
    Subjects.HR_AUDIT,
  ],
  [Subjects.ADMIN]: [Subjects.USER, Subjects.AGENCE, Subjects.SESSION, Subjects.AUDIT_LOG],
  [Subjects.RBAC]: [Subjects.ROLE, Subjects.PERMISSION],
  [Subjects.TERRAIN]: [Subjects.AGENT_TERRAIN, Subjects.OPERATION_TERRAIN, Subjects.PROSPECTION, Subjects.PROSPECTION_PRIME, Subjects.ARRONDISSEMENT, Subjects.MARCHE, Subjects.PROSPECTION_CONFIG],
};
