/**
 * Service de Rotation des Codes de Sécurité Caisse
 *
 * Gère l'expiration automatique et le renouvellement des codes de sécurité:
 * - Vérification des politiques de rotation par agence
 * - Génération automatique de nouveaux codes à l'expiration
 * - Notification des expirations imminentes
 * - Suivi de l'utilisation et révocation automatique
 */

import { db } from "../../db";
import {
  caisseSecurityCodes,
  caisseCodeUsages,
  caisseUserAuthorizations,
  accessCodeRotationPolicies,
  accessCodeUsageLogs,
  type CaisseSecurityCode,
  type AccessCodeRotationPolicy,
} from "@shared/schema";
import { users, agences, notifications } from "@shared/schema";
import { eq, and, lt, gte, isNull, desc, sql, lte, or, count } from "drizzle-orm";
import { createLogger } from "../../lib/logger";
import bcrypt from "bcrypt";
import crypto from "crypto";

const logger = createLogger('SecurityCodeRotationService');

// ============================================================================
// TYPES
// ============================================================================

export interface GenerateCodeParams {
  agenceId?: string;
  caisseId?: string;
  codeType: 'EMERGENCY' | 'DAILY' | 'PERMANENT';
  createdBy: string;
  description?: string;
  maxUsages?: number;
  expiresInHours?: number;
  authorizationDurationHours?: number;
  assignedToUserId?: string;
}

export interface GenerateCodeResult {
  success: boolean;
  code?: string;
  codeId?: string;
  expiresAt?: Date;
  error?: string;
}

export interface ValidateCodeParams {
  code: string;
  agenceId?: string;
  caisseId?: string;
  userId: string;
  ipAddress?: string;
  userAgent?: string;
  action?: string;
}

export interface ValidateCodeResult {
  success: boolean;
  authorization?: {
    id: string;
    expiresAt: Date;
  };
  error?: string;
  errorCode?: 'CODE_NOT_FOUND' | 'CODE_EXPIRED' | 'CODE_INACTIVE' | 'MAX_USAGES_REACHED' | 'SCOPE_MISMATCH';
}

export interface RotationCheckResult {
  codesNearExpiry: ExpiringCode[];
  codesExpired: ExpiredCode[];
  codesMaxUsage: MaxUsageCode[];
  autoGeneratedCodes: AutoGeneratedCode[];
}

export interface ExpiringCode {
  id: string;
  codeType: string;
  agenceId?: string | null;
  caisseId?: string | null;
  expiresAt: Date;
  daysUntilExpiry: number;
}

export interface ExpiredCode {
  id: string;
  codeType: string;
  agenceId?: string | null;
  caisseId?: string | null;
  expiredAt: Date;
}

export interface MaxUsageCode {
  id: string;
  codeType: string;
  usageCount: number;
  maxUsages: number;
}

export interface AutoGeneratedCode {
  codeId: string;
  codeType: string;
  agenceId?: string;
  reason: string;
}

export interface CodeStatistics {
  totalActive: number;
  totalExpired: number;
  totalByType: Record<string, number>;
  usageCountToday: number;
  expiringIn7Days: number;
}

// ============================================================================
// SERVICE
// ============================================================================

export class SecurityCodeRotationService {

  /**
   * Génère un nouveau code de sécurité
   */
  async generateCode(params: GenerateCodeParams): Promise<GenerateCodeResult> {
    const {
      agenceId,
      caisseId,
      codeType,
      createdBy,
      description,
      maxUsages,
      expiresInHours,
      authorizationDurationHours = 4,
      assignedToUserId,
    } = params;

    try {
      // Générer un code aléatoire de 6 caractères alphanumériques
      const plainCode = this.generateRandomCode();
      const codeHash = await bcrypt.hash(plainCode, 10);

      // Calculer la date d'expiration selon le type
      let expiresAt: Date | null = null;
      if (expiresInHours) {
        expiresAt = new Date();
        expiresAt.setHours(expiresAt.getHours() + expiresInHours);
      } else {
        // Appliquer la politique de rotation par défaut
        const policy = await this.getRotationPolicy(agenceId);
        if (policy && policy.rotationFrequencyDays) {
          expiresAt = new Date();
          expiresAt.setDate(expiresAt.getDate() + policy.rotationFrequencyDays);
        } else {
          // Fallback: 30 jours pour DAILY/EMERGENCY, illimité pour PERMANENT
          if (codeType !== 'PERMANENT') {
            expiresAt = new Date();
            expiresAt.setDate(expiresAt.getDate() + 30);
          }
        }
      }

      // Créer le code
      const [newCode] = await db.insert(caisseSecurityCodes).values({
        agenceId: agenceId || null,
        caisseId: caisseId || null,
        codeType,
        codeHash,
        active: true,
        expiresAt,
        maxUsages: maxUsages || null,
        usageCount: 0,
        authorizationDurationHours,
        createdBy,
        description,
        agentId: assignedToUserId || null, // User assigned to receive this code
      }).returning();

      logger.info({
        codeId: newCode.id,
        codeType,
        agenceId,
        caisseId,
        expiresAt,
        createdBy,
      }, 'Code de sécurité généré');

      return {
        success: true,
        code: plainCode,
        codeId: newCode.id,
        expiresAt: expiresAt || undefined,
      };
    } catch (error: any) {
      logger.error({ err: error }, 'Erreur génération code sécurité');
      return {
        success: false,
        error: error.message || 'Erreur lors de la génération du code',
      };
    }
  }

  /**
   * Valide un code de sécurité et crée une autorisation
   */
  async validateCode(params: ValidateCodeParams): Promise<ValidateCodeResult> {
    const { code, agenceId, caisseId, userId, ipAddress, userAgent, action } = params;

    try {
      // Récupérer les codes actifs correspondants au scope
      const conditions = [eq(caisseSecurityCodes.active, true)];

      // Filtrer par scope (agence ou caisse)
      if (caisseId) {
        conditions.push(
          or(
            eq(caisseSecurityCodes.caisseId, caisseId),
            and(isNull(caisseSecurityCodes.caisseId), eq(caisseSecurityCodes.agenceId, agenceId!))
          )!
        );
      } else if (agenceId) {
        conditions.push(
          or(
            eq(caisseSecurityCodes.agenceId, agenceId),
            isNull(caisseSecurityCodes.agenceId)
          )!
        );
      }

      const activeCodes = await db.select()
        .from(caisseSecurityCodes)
        .where(and(...conditions));

      // Vérifier chaque code
      for (const securityCode of activeCodes) {
        const isMatch = await bcrypt.compare(code, securityCode.codeHash);
        if (!isMatch) continue;

        // Code trouvé - vérifier la validité
        const now = new Date();

        // Vérifier l'expiration
        if (securityCode.expiresAt && new Date(securityCode.expiresAt) < now) {
          await this.logUsage(securityCode.id, userId, action || 'VALIDATE', false, 'Code expiré', ipAddress, userAgent);
          return {
            success: false,
            error: 'Code expiré',
            errorCode: 'CODE_EXPIRED',
          };
        }

        // Vérifier le nombre d'utilisations
        if (securityCode.maxUsages && securityCode.usageCount! >= securityCode.maxUsages) {
          await this.logUsage(securityCode.id, userId, action || 'VALIDATE', false, 'Nombre max d\'utilisations atteint', ipAddress, userAgent);
          return {
            success: false,
            error: 'Nombre maximum d\'utilisations atteint',
            errorCode: 'MAX_USAGES_REACHED',
          };
        }

        // Code valide - créer l'autorisation
        const authExpiresAt = new Date();
        authExpiresAt.setHours(authExpiresAt.getHours() + (securityCode.authorizationDurationHours || 4));

        const [authorization] = await db.insert(caisseUserAuthorizations).values({
          userId,
          caisseId: securityCode.caisseId || caisseId || null,
          agenceId: securityCode.agenceId || agenceId || null,
          codeId: securityCode.id,
          reason: action || 'Validation code sécurité',
          expiresAt: authExpiresAt,
          ipAddress: ipAddress || null,
          userAgent: userAgent || null,
        }).returning();

        // Incrémenter le compteur d'utilisation
        await db.update(caisseSecurityCodes)
          .set({ usageCount: sql`${caisseSecurityCodes.usageCount} + 1` })
          .where(eq(caisseSecurityCodes.id, securityCode.id));

        // Log de succès
        await this.logUsage(securityCode.id, userId, action || 'VALIDATE', true, undefined, ipAddress, userAgent);

        logger.info({
          codeId: securityCode.id,
          authorizationId: authorization.id,
          userId,
          expiresAt: authExpiresAt,
        }, 'Code validé, autorisation créée');

        return {
          success: true,
          authorization: {
            id: authorization.id,
            expiresAt: authExpiresAt,
          },
        };
      }

      // Aucun code correspondant
      await this.logUsage(null, userId, action || 'VALIDATE', false, 'Code non trouvé', ipAddress, userAgent);
      return {
        success: false,
        error: 'Code invalide',
        errorCode: 'CODE_NOT_FOUND',
      };
    } catch (error: any) {
      logger.error({ err: error }, 'Erreur validation code');
      return {
        success: false,
        error: error.message || 'Erreur lors de la validation',
      };
    }
  }

  /**
   * Vérifie et applique les politiques de rotation
   */
  async checkAndApplyRotation(): Promise<RotationCheckResult> {
    const result: RotationCheckResult = {
      codesNearExpiry: [],
      codesExpired: [],
      codesMaxUsage: [],
      autoGeneratedCodes: [],
    };

    try {
      const now = new Date();
      const in7Days = new Date();
      in7Days.setDate(in7Days.getDate() + 7);

      // 1. Trouver les codes qui expirent bientôt
      const nearExpiryCodes = await db.select({
        id: caisseSecurityCodes.id,
        codeType: caisseSecurityCodes.codeType,
        agenceId: caisseSecurityCodes.agenceId,
        caisseId: caisseSecurityCodes.caisseId,
        expiresAt: caisseSecurityCodes.expiresAt,
        createdBy: caisseSecurityCodes.createdBy,
      })
      .from(caisseSecurityCodes)
      .where(and(
        eq(caisseSecurityCodes.active, true),
        gte(caisseSecurityCodes.expiresAt, now),
        lte(caisseSecurityCodes.expiresAt, in7Days)
      ));

      for (const code of nearExpiryCodes) {
        const daysUntilExpiry = Math.ceil(
          (new Date(code.expiresAt!).getTime() - now.getTime()) / (1000 * 60 * 60 * 24)
        );

        result.codesNearExpiry.push({
          id: code.id,
          codeType: code.codeType || 'EMERGENCY',
          agenceId: code.agenceId,
          caisseId: code.caisseId,
          expiresAt: new Date(code.expiresAt!),
          daysUntilExpiry,
        });

        // Notifier le créateur du code
        if (code.createdBy) {
          await this.sendExpiryNotification(code.createdBy, code.id, daysUntilExpiry);
        }
      }

      // 2. Désactiver les codes expirés
      const expiredCodes = await db.select({
        id: caisseSecurityCodes.id,
        codeType: caisseSecurityCodes.codeType,
        agenceId: caisseSecurityCodes.agenceId,
        caisseId: caisseSecurityCodes.caisseId,
        expiresAt: caisseSecurityCodes.expiresAt,
      })
      .from(caisseSecurityCodes)
      .where(and(
        eq(caisseSecurityCodes.active, true),
        lt(caisseSecurityCodes.expiresAt, now)
      ));

      for (const code of expiredCodes) {
        // Désactiver le code
        await db.update(caisseSecurityCodes)
          .set({ active: false })
          .where(eq(caisseSecurityCodes.id, code.id));

        result.codesExpired.push({
          id: code.id,
          codeType: code.codeType || 'EMERGENCY',
          agenceId: code.agenceId,
          caisseId: code.caisseId,
          expiredAt: new Date(code.expiresAt!),
        });

        // Vérifier si on doit auto-générer un nouveau code
        const policy = await this.getRotationPolicy(code.agenceId || undefined);
        if (policy?.autoGenerateOnExpiry && code.codeType === 'DAILY') {
          // Auto-générer un nouveau code DAILY
          const newCodeResult = await this.generateCode({
            agenceId: code.agenceId || undefined,
            caisseId: code.caisseId || undefined,
            codeType: 'DAILY',
            createdBy: 'SYSTEM',
            description: `Auto-généré après expiration de ${code.id}`,
          });

          if (newCodeResult.success) {
            result.autoGeneratedCodes.push({
              codeId: newCodeResult.codeId!,
              codeType: 'DAILY',
              agenceId: code.agenceId || undefined,
              reason: 'Expiration du code précédent',
            });

            logger.info({
              oldCodeId: code.id,
              newCodeId: newCodeResult.codeId,
              agenceId: code.agenceId,
            }, 'Code auto-généré après expiration');
          }
        }
      }

      // 3. Vérifier les codes ayant atteint le max d'utilisations
      const maxUsageCodes = await db.select({
        id: caisseSecurityCodes.id,
        codeType: caisseSecurityCodes.codeType,
        usageCount: caisseSecurityCodes.usageCount,
        maxUsages: caisseSecurityCodes.maxUsages,
      })
      .from(caisseSecurityCodes)
      .where(and(
        eq(caisseSecurityCodes.active, true),
        sql`${caisseSecurityCodes.maxUsages} IS NOT NULL`,
        sql`${caisseSecurityCodes.usageCount} >= ${caisseSecurityCodes.maxUsages}`
      ));

      for (const code of maxUsageCodes) {
        // Désactiver le code
        await db.update(caisseSecurityCodes)
          .set({ active: false })
          .where(eq(caisseSecurityCodes.id, code.id));

        result.codesMaxUsage.push({
          id: code.id,
          codeType: code.codeType || 'EMERGENCY',
          usageCount: code.usageCount || 0,
          maxUsages: code.maxUsages!,
        });
      }

      logger.info({
        nearExpiry: result.codesNearExpiry.length,
        expired: result.codesExpired.length,
        maxUsage: result.codesMaxUsage.length,
        autoGenerated: result.autoGeneratedCodes.length,
      }, 'Rotation des codes effectuée');

      return result;
    } catch (error: any) {
      logger.error({ err: error }, 'Erreur rotation codes');
      return result;
    }
  }

  /**
   * Récupère les codes actifs pour une agence/caisse
   */
  async getActiveCodes(agenceId?: string, caisseId?: string): Promise<CaisseSecurityCode[]> {
    const conditions = [eq(caisseSecurityCodes.active, true)];

    if (caisseId) {
      conditions.push(eq(caisseSecurityCodes.caisseId, caisseId));
    } else if (agenceId) {
      conditions.push(eq(caisseSecurityCodes.agenceId, agenceId));
    }

    const codes = await db.select()
      .from(caisseSecurityCodes)
      .where(and(...conditions))
      .orderBy(desc(caisseSecurityCodes.createdAt));

    return codes;
  }

  /**
   * Révoque un code de sécurité
   */
  async revokeCode(codeId: string, revokedBy: string, reason?: string): Promise<boolean> {
    try {
      await db.update(caisseSecurityCodes)
        .set({ active: false })
        .where(eq(caisseSecurityCodes.id, codeId));

      // Log l'action
      await db.insert(accessCodeUsageLogs).values({
        codeId,
        usedBy: revokedBy,
        action: 'REVOKED',
        success: true,
        failureReason: reason || undefined,
      });

      logger.info({ codeId, revokedBy, reason }, 'Code révoqué');
      return true;
    } catch (error: any) {
      logger.error({ err: error, codeId }, 'Erreur révocation code');
      return false;
    }
  }

  /**
   * Récupère les statistiques des codes
   */
  async getStatistics(agenceId?: string): Promise<CodeStatistics> {
    const now = new Date();
    const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const in7Days = new Date();
    in7Days.setDate(in7Days.getDate() + 7);

    const baseConditions = agenceId
      ? [eq(caisseSecurityCodes.agenceId, agenceId)]
      : [];

    // Total actifs
    const [activeResult] = await db.select({ count: count() })
      .from(caisseSecurityCodes)
      .where(and(eq(caisseSecurityCodes.active, true), ...baseConditions));

    // Total expirés/inactifs
    const [expiredResult] = await db.select({ count: count() })
      .from(caisseSecurityCodes)
      .where(and(eq(caisseSecurityCodes.active, false), ...baseConditions));

    // Par type
    const byType = await db.select({
      codeType: caisseSecurityCodes.codeType,
      count: count(),
    })
    .from(caisseSecurityCodes)
    .where(and(eq(caisseSecurityCodes.active, true), ...baseConditions))
    .groupBy(caisseSecurityCodes.codeType);

    // Utilisations aujourd'hui
    const [usageResult] = await db.select({ count: count() })
      .from(caisseCodeUsages)
      .where(and(
        gte(caisseCodeUsages.usedAt, startOfDay),
        eq(caisseCodeUsages.success, true)
      ));

    // Expirant dans 7 jours
    const [expiringResult] = await db.select({ count: count() })
      .from(caisseSecurityCodes)
      .where(and(
        eq(caisseSecurityCodes.active, true),
        gte(caisseSecurityCodes.expiresAt, now),
        lte(caisseSecurityCodes.expiresAt, in7Days),
        ...baseConditions
      ));

    const totalByType: Record<string, number> = {};
    for (const item of byType) {
      totalByType[item.codeType || 'UNKNOWN'] = item.count;
    }

    return {
      totalActive: activeResult?.count || 0,
      totalExpired: expiredResult?.count || 0,
      totalByType,
      usageCountToday: usageResult?.count || 0,
      expiringIn7Days: expiringResult?.count || 0,
    };
  }

  /**
   * Récupère la politique de rotation pour une agence
   */
  async getRotationPolicy(agenceId?: string): Promise<AccessCodeRotationPolicy | null> {
    // D'abord chercher la politique spécifique à l'agence
    if (agenceId) {
      const [agencePolicy] = await db.select()
        .from(accessCodeRotationPolicies)
        .where(and(
          eq(accessCodeRotationPolicies.agenceId, agenceId),
          eq(accessCodeRotationPolicies.isActive, true)
        ));

      if (agencePolicy) {
        return agencePolicy;
      }
    }

    // Sinon, chercher la politique globale
    const [globalPolicy] = await db.select()
      .from(accessCodeRotationPolicies)
      .where(and(
        isNull(accessCodeRotationPolicies.agenceId),
        eq(accessCodeRotationPolicies.isActive, true)
      ));

    return globalPolicy || null;
  }

  /**
   * Met à jour ou crée une politique de rotation
   */
  async upsertRotationPolicy(params: {
    agenceId?: string;
    rotationFrequencyDays?: number;
    maxUsageBeforeRotation?: number;
    notifyDaysBeforeExpiry?: number;
    autoGenerateOnExpiry?: boolean;
    updatedBy: string;
  }): Promise<AccessCodeRotationPolicy> {
    const {
      agenceId,
      rotationFrequencyDays,
      maxUsageBeforeRotation,
      notifyDaysBeforeExpiry,
      autoGenerateOnExpiry,
    } = params;

    const existingPolicy = await this.getRotationPolicy(agenceId);

    if (existingPolicy && (existingPolicy.agenceId === agenceId || (!existingPolicy.agenceId && !agenceId))) {
      // Mettre à jour
      const [updated] = await db.update(accessCodeRotationPolicies)
        .set({
          rotationFrequencyDays: rotationFrequencyDays ?? existingPolicy.rotationFrequencyDays,
          maxUsageBeforeRotation: maxUsageBeforeRotation ?? existingPolicy.maxUsageBeforeRotation,
          notifyDaysBeforeExpiry: notifyDaysBeforeExpiry ?? existingPolicy.notifyDaysBeforeExpiry,
          autoGenerateOnExpiry: autoGenerateOnExpiry ?? existingPolicy.autoGenerateOnExpiry,
          updatedAt: new Date(),
        })
        .where(eq(accessCodeRotationPolicies.id, existingPolicy.id))
        .returning();

      logger.info({ policyId: updated.id, agenceId }, 'Politique de rotation mise à jour');
      return updated;
    } else {
      // Créer
      const [created] = await db.insert(accessCodeRotationPolicies).values({
        agenceId: agenceId || null,
        rotationFrequencyDays: rotationFrequencyDays ?? 30,
        maxUsageBeforeRotation,
        notifyDaysBeforeExpiry: notifyDaysBeforeExpiry ?? 7,
        autoGenerateOnExpiry: autoGenerateOnExpiry ?? false,
        isActive: true,
      }).returning();

      logger.info({ policyId: created.id, agenceId }, 'Politique de rotation créée');
      return created;
    }
  }

  // ============================================================================
  // MÉTHODES PRIVÉES
  // ============================================================================

  private generateRandomCode(): string {
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // Exclus I, O, 0, 1 pour éviter confusion
    let code = '';
    for (let i = 0; i < 6; i++) {
      code += chars.charAt(crypto.randomInt(0, chars.length));
    }
    return code;
  }

  private async logUsage(
    codeId: string | null,
    userId: string,
    action: string,
    success: boolean,
    failureReason?: string,
    ipAddress?: string,
    userAgent?: string
  ): Promise<void> {
    try {
      // Log dans caisseCodeUsages si codeId existe
      if (codeId) {
        await db.insert(caisseCodeUsages).values({
          codeId,
          userId,
          success,
          failureReason: failureReason || null,
          ipAddress: ipAddress || null,
          userAgent: userAgent || null,
        });
      }

      // Log dans accessCodeUsageLogs pour audit complet
      await db.insert(accessCodeUsageLogs).values({
        codeId: codeId || '00000000-0000-0000-0000-000000000000',
        usedBy: userId,
        action,
        success,
        failureReason: failureReason || null,
        ipAddress: ipAddress || null,
        userAgent: userAgent || null,
      });
    } catch (error) {
      logger.error({ err: error }, 'Erreur logging usage code');
    }
  }

  private async sendExpiryNotification(userId: string, codeId: string, daysUntilExpiry: number): Promise<void> {
    try {
      await db.insert(notifications).values({
        userId,
        type: 'system',
        titre: 'Code de sécurité expire bientôt',
        message: `Votre code de sécurité expire dans ${daysUntilExpiry} jour(s). Pensez à le renouveler.`,
        priorite: daysUntilExpiry <= 3 ? 'HIGH' : 'NORMAL',
        lue: false,
        referenceId: codeId,
        referenceType: 'caisse_security_code',
      });
    } catch (error) {
      logger.error({ err: error }, 'Erreur envoi notification expiration');
    }
  }
}

// Export singleton
export const securityCodeRotationService = new SecurityCodeRotationService();
