/**
 * Catalogue des événements métier transportés par le bus de notifications.
 *
 * Le type reste volontairement centralisé : il sert de clé de registre pour les
 * handlers, les diffusions WebSocket et les événements d'audit.
 */
export type DomainEventType =
  | "CREDIT_REQUEST_CREATED"
  | "CREDIT_APPROVED"
  | "CREDIT_REJECTED"
  | "CREDIT_DISBURSED"
  | "CREDIT_OVERDUE"
  | "CREDIT_INVESTIGATION_ASSIGNED"
  | "CREDIT_INVESTIGATION_SUBMITTED"
  | "CREDIT_PAID_OFF"
  | "CREDIT_REFUND_APPROVED"
  | "CREDIT_REFUND_PAID"
  | "TRANSFER_REQUESTED"
  | "TRANSFER_VALIDATED"
  | "TRANSFER_REJECTED"
  | "TRANSFER_EXECUTED"
  | "TRANSFER_CANCELLED"
  | "TRANSFER_REVERSED"
  | "SCHEDULED_TRANSFER_EXECUTED"
  | "SCHEDULED_TRANSFER_FAILED"
  | "HR_LEAVE_REQUESTED"
  | "HR_LEAVE_APPROVED"
  | "HR_LEAVE_REJECTED"
  | "HR_DOCUMENT_REQUEST_CREATED"
  | "HR_SANCTION_CREATED"
  | "HR_SANCTION_NOTIFIED"
  | "HR_SANCTION_FINALIZED"
  | "TONTINE_MEMBER_JOINED"
  | "TONTINE_CONTRIBUTION_RECEIVED"
  | "TONTINE_CONTRIBUTION_OVERDUE"
  | "TONTINE_PENALTY_APPLIED"
  | "TONTINE_DISTRIBUTION_APPROVED"
  | "TONTINE_DISTRIBUTION_PAID"
  | "TONTINE_CYCLE_STARTED"
  | "TONTINE_STATUS_CHANGED"
  | "TONTINE_MEMBER_EXIT"
  | "ACCOUNT_CREATED"
  | "ACCOUNT_ACTIVATED"
  | "ACCOUNT_DEPOSIT"
  | "ACCOUNT_WITHDRAWAL"
  | "ACCOUNT_BLOCKED"
  | "ACCOUNT_UNBLOCKED"
  | "ACCOUNT_CLOSED"
  | "INTEREST_CAPITALIZED"
  | "USER_PASSWORD_RESET"
  | "SESSION_FORCE_CLOSED"
  | "CLIENT_CREATED"
  | "USER_REGISTERED"
  | "USER_PASSWORD_CHANGED"
  | "EMPLOYEE_CREATED"
  | "PROSPECTION_CREATED"
  | "PROSPECT_CONVERTED"
  | "PAIEMENT_TERRAIN_VALIDATED"
  | "CREDIT_INSTALLMENT_LATE"
  | "SYSTEM_JOB_FAILED"
  | "CLIENT_SEGMENT_CHANGED"
  | "ACCOUNT_SUSPENDED"
  | "ACCOUNT_UNSUSPENDED"
  | "CLOSURE_INITIATED"
  | "CLOSURE_APPROVED";

/**
 * Enveloppe standard d'un événement métier émis par un service applicatif.
 *
 * @typeParam T - Payload métier associé au type d'événement.
 */
export interface DomainEvent<T = unknown> {
  type: DomainEventType;
  data: T;
  timestamp: Date;
  agenceId?: string;
  userId?: string;
}
