import type { CaisseSecurityCode, AccessCodeRotationPolicy } from "@shared/schema";

export interface GenerateCodeParams {
  agenceId?: string;
  caisseId?: string;
  codeType: 'EMERGENCY' | 'DAILY' | 'PERMANENT';
  createdBy: string;
  description?: string;
  maxUsages?: number;
  expiresInHours?: number;
  authorizationDurationHours?: number;
  assignedToUserId?: string;
}

export interface GenerateCodeResult {
  success: boolean;
  code?: string;
  codeId?: string;
  expiresAt?: Date;
  error?: string;
}

export interface ValidateCodeParams {
  code: string;
  agenceId?: string;
  caisseId?: string;
  userId: string;
  ipAddress?: string;
  userAgent?: string;
  action?: string;
}

export interface ValidateCodeResult {
  success: boolean;
  authorization?: {
    id: string;
    expiresAt: Date;
  };
  error?: string;
  errorCode?: 'CODE_NOT_FOUND' | 'CODE_EXPIRED' | 'CODE_INACTIVE' | 'MAX_USAGES_REACHED' | 'SCOPE_MISMATCH';
}

export interface RotationCheckResult {
  codesNearExpiry: ExpiringCode[];
  codesExpired: ExpiredCode[];
  codesMaxUsage: MaxUsageCode[];
  autoGeneratedCodes: AutoGeneratedCode[];
}

export interface ExpiringCode {
  id: string;
  codeType: string;
  agenceId?: string | null;
  caisseId?: string | null;
  expiresAt: Date;
  daysUntilExpiry: number;
}

export interface ExpiredCode {
  id: string;
  codeType: string;
  agenceId?: string | null;
  caisseId?: string | null;
  expiredAt: Date;
}

export interface MaxUsageCode {
  id: string;
  codeType: string;
  usageCount: number;
  maxUsages: number;
}

export interface AutoGeneratedCode {
  codeId: string;
  codeType: string;
  agenceId?: string;
  reason: string;
}

export interface CodeStatistics {
  totalActive: number;
  totalExpired: number;
  totalByType: Record<string, number>;
  usageCountToday: number;
  expiringIn7Days: number;
}
