import { db } from "../../db";
import { caisseSecurityCodes, accessCodeRotationPolicies, notifications } from "@shared/schema";
import type { AccessCodeRotationPolicy } from "@shared/schema";
import { eq, and, isNull, lt, gte, lte, sql } from "drizzle-orm";
import { createLogger } from "../../lib/logger";
import type { RotationCheckResult } from "./security-code-types";
import { securityCodeGenerator } from "./security-code-generator";

const logger = createLogger('SecurityCodePolicy');

export class SecurityCodePolicy {
  /**
   * Vérifie et applique les politiques de rotation
   */
  async checkAndApplyRotation(): Promise<RotationCheckResult> {
    const result: RotationCheckResult = {
      codesNearExpiry: [],
      codesExpired: [],
      codesMaxUsage: [],
      autoGeneratedCodes: [],
    };

    try {
      const now = new Date();
      const in7Days = new Date();
      in7Days.setDate(in7Days.getDate() + 7);

      const nearExpiryCodes = await db.select({
        id: caisseSecurityCodes.id,
        codeType: caisseSecurityCodes.codeType,
        agenceId: caisseSecurityCodes.agenceId,
        caisseId: caisseSecurityCodes.caisseId,
        expiresAt: caisseSecurityCodes.expiresAt,
        createdBy: caisseSecurityCodes.createdBy,
      })
      .from(caisseSecurityCodes)
      .where(and(
        eq(caisseSecurityCodes.active, true),
        gte(caisseSecurityCodes.expiresAt, now),
        lte(caisseSecurityCodes.expiresAt, in7Days)
      ));

      for (const code of nearExpiryCodes) {
        const daysUntilExpiry = Math.ceil(
          (new Date(code.expiresAt!).getTime() - now.getTime()) / (1000 * 60 * 60 * 24)
        );

        result.codesNearExpiry.push({
          id: code.id,
          codeType: code.codeType || 'EMERGENCY',
          agenceId: code.agenceId,
          caisseId: code.caisseId,
          expiresAt: new Date(code.expiresAt!),
          daysUntilExpiry,
        });

        if (code.createdBy) {
          await this.sendExpiryNotification(code.createdBy, code.id, daysUntilExpiry);
        }
      }

      const expiredCodes = await db.select({
        id: caisseSecurityCodes.id,
        codeType: caisseSecurityCodes.codeType,
        agenceId: caisseSecurityCodes.agenceId,
        caisseId: caisseSecurityCodes.caisseId,
        expiresAt: caisseSecurityCodes.expiresAt,
      })
      .from(caisseSecurityCodes)
      .where(and(
        eq(caisseSecurityCodes.active, true),
        lt(caisseSecurityCodes.expiresAt, now)
      ));

      for (const code of expiredCodes) {
        await db.update(caisseSecurityCodes)
          .set({ active: false })
          .where(eq(caisseSecurityCodes.id, code.id));

        result.codesExpired.push({
          id: code.id,
          codeType: code.codeType || 'EMERGENCY',
          agenceId: code.agenceId,
          caisseId: code.caisseId,
          expiredAt: new Date(code.expiresAt!),
        });

        const policy = await this.getRotationPolicy(code.agenceId || undefined);
        if (policy?.autoGenerateOnExpiry && code.codeType === 'DAILY') {
          const newCodeResult = await securityCodeGenerator.generateCode({
            agenceId: code.agenceId || undefined,
            caisseId: code.caisseId || undefined,
            codeType: 'DAILY',
            createdBy: 'SYSTEM',
            description: `Auto-généré après expiration de ${code.id}`,
          });

          if (newCodeResult.success) {
            result.autoGeneratedCodes.push({
              codeId: newCodeResult.codeId!,
              codeType: 'DAILY',
              agenceId: code.agenceId || undefined,
              reason: 'Expiration du code précédent',
            });

            logger.info({
              oldCodeId: code.id,
              newCodeId: newCodeResult.codeId,
              agenceId: code.agenceId,
            }, 'Code auto-généré après expiration');
          }
        }
      }

      const maxUsageCodes = await db.select({
        id: caisseSecurityCodes.id,
        codeType: caisseSecurityCodes.codeType,
        usageCount: caisseSecurityCodes.usageCount,
        maxUsages: caisseSecurityCodes.maxUsages,
      })
      .from(caisseSecurityCodes)
      .where(and(
        eq(caisseSecurityCodes.active, true),
        sql`${caisseSecurityCodes.maxUsages} IS NOT NULL`,
        sql`${caisseSecurityCodes.usageCount} >= ${caisseSecurityCodes.maxUsages}`
      ));

      for (const code of maxUsageCodes) {
        await db.update(caisseSecurityCodes)
          .set({ active: false })
          .where(eq(caisseSecurityCodes.id, code.id));

        result.codesMaxUsage.push({
          id: code.id,
          codeType: code.codeType || 'EMERGENCY',
          usageCount: code.usageCount || 0,
          maxUsages: code.maxUsages!,
        });
      }

      logger.info({
        nearExpiry: result.codesNearExpiry.length,
        expired: result.codesExpired.length,
        maxUsage: result.codesMaxUsage.length,
        autoGenerated: result.autoGeneratedCodes.length,
      }, 'Rotation des codes effectuée');

      return result;
    } catch (error: unknown) {
      logger.error({ err: error }, 'Erreur rotation codes');
      return result;
    }
  }

  /**
   * Récupère la politique de rotation pour une agence
   */
  async getRotationPolicy(agenceId?: string): Promise<AccessCodeRotationPolicy | null> {
    if (agenceId) {
      const [agencePolicy] = await db.select()
        .from(accessCodeRotationPolicies)
        .where(and(
          eq(accessCodeRotationPolicies.agenceId, agenceId),
          eq(accessCodeRotationPolicies.isActive, true)
        ));

      if (agencePolicy) {
        return agencePolicy;
      }
    }

    const [globalPolicy] = await db.select()
      .from(accessCodeRotationPolicies)
      .where(and(
        isNull(accessCodeRotationPolicies.agenceId),
        eq(accessCodeRotationPolicies.isActive, true)
      ));

    return globalPolicy || null;
  }

  /**
   * Met à jour ou crée une politique de rotation
   */
  async upsertRotationPolicy(params: {
    agenceId?: string;
    rotationFrequencyDays?: number;
    maxUsageBeforeRotation?: number;
    notifyDaysBeforeExpiry?: number;
    autoGenerateOnExpiry?: boolean;
    updatedBy: string;
  }): Promise<AccessCodeRotationPolicy> {
    const {
      agenceId,
      rotationFrequencyDays,
      maxUsageBeforeRotation,
      notifyDaysBeforeExpiry,
      autoGenerateOnExpiry,
    } = params;

    const existingPolicy = await this.getRotationPolicy(agenceId);

    if (existingPolicy && (existingPolicy.agenceId === agenceId || (!existingPolicy.agenceId && !agenceId))) {
      const [updated] = await db.update(accessCodeRotationPolicies)
        .set({
          rotationFrequencyDays: rotationFrequencyDays ?? existingPolicy.rotationFrequencyDays,
          maxUsageBeforeRotation: maxUsageBeforeRotation ?? existingPolicy.maxUsageBeforeRotation,
          notifyDaysBeforeExpiry: notifyDaysBeforeExpiry ?? existingPolicy.notifyDaysBeforeExpiry,
          autoGenerateOnExpiry: autoGenerateOnExpiry ?? existingPolicy.autoGenerateOnExpiry,
          updatedAt: new Date(),
        })
        .where(eq(accessCodeRotationPolicies.id, existingPolicy.id))
        .returning();

      logger.info({ policyId: updated.id, agenceId }, 'Politique de rotation mise à jour');
      return updated;
    } else {
      const [created] = await db.insert(accessCodeRotationPolicies).values({
        agenceId: agenceId || null,
        rotationFrequencyDays: rotationFrequencyDays ?? 30,
        maxUsageBeforeRotation,
        notifyDaysBeforeExpiry: notifyDaysBeforeExpiry ?? 7,
        autoGenerateOnExpiry: autoGenerateOnExpiry ?? false,
        isActive: true,
      }).returning();

      logger.info({ policyId: created.id, agenceId }, 'Politique de rotation créée');
      return created;
    }
  }

  private async sendExpiryNotification(userId: string, codeId: string, daysUntilExpiry: number): Promise<void> {
    try {
      await db.insert(notifications).values({
        userId,
        type: 'system',
        titre: 'Code de sécurité expire bientôt',
        message: `Votre code de sécurité expire dans ${daysUntilExpiry} jour(s). Pensez à le renouveler.`,
        priorite: daysUntilExpiry <= 3 ? 'HIGH' : 'NORMAL',
        lue: false,
        referenceId: codeId,
        referenceType: 'caisse_security_code',
      });
    } catch (error) {
      logger.error({ err: error }, 'Erreur envoi notification expiration');
    }
  }
}

export const securityCodePolicy = new SecurityCodePolicy();
