/**
 * Navigation Search Provider
 *
 * Client-side provider that indexes all pages & sub-pages.
 * Returns instant results for page navigation.
 */

import {
  LayoutDashboard, Users, CreditCard, Wallet, DollarSign, Landmark,
  MapPin, CheckCircle, ArrowLeftRight, Lock, BarChart3, BookOpen,
  UserCog, Settings, MessageSquare, User, TrendingUp,
  FilePlus, ClipboardList, Search as SearchIcon, Building2,
  FileText, Shield, Database, Bell, Palette, Coins,
} from 'lucide-react';
import { Actions, Subjects } from '@shared/ability';
import { scoreResult } from '../engine';
import type { SearchProvider, SearchResult, SearchContext } from '../types';

/**
 * Static index of all navigable pages in the app.
 */
const NAVIGATION_ITEMS: SearchResult[] = [
  // ─── Principal ──────────────────────
  {
    id: 'nav-dashboard',
    title: 'Tableau de bord',
    keywords: ['dashboard', 'accueil', 'home', 'résumé'],
    group: 'Navigation',
    icon: LayoutDashboard,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'dashboard',
    permission: { action: Actions.VIEW, subject: Subjects.DASHBOARD },
  },

  // ─── Services Clients ──────────────
  {
    id: 'nav-clients',
    title: 'Clients',
    keywords: ['client', 'portefeuille clients', 'liste clients'],
    group: 'Navigation',
    icon: Users,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'clients',
    permission: { action: Actions.VIEW, subject: Subjects.CLIENTS },
  },
  {
    id: 'nav-credits',
    title: 'Crédits - Synthèse',
    keywords: ['crédits', 'prêts', 'loans', 'résumé crédits'],
    group: 'Navigation',
    icon: CreditCard,
    iconBg: 'bg-status-success-bg text-status-success',
    type: 'navigation',
    moduleKey: 'credits',
    subModule: 'dashboard',
    permission: { action: Actions.VIEW, subject: Subjects.CREDITS },
  },
  {
    id: 'nav-credits-portefeuille',
    title: 'Crédits - Portefeuille',
    keywords: ['crédits actifs', 'prêts en cours', 'portefeuille'],
    group: 'Navigation',
    icon: CreditCard,
    iconBg: 'bg-status-success-bg text-status-success',
    type: 'navigation',
    moduleKey: 'credits',
    subModule: 'credits',
    permission: { action: Actions.VIEW, subject: Subjects.CREDITS },
  },
  {
    id: 'nav-credits-demandes',
    title: 'Crédits - À traiter',
    keywords: ['demandes crédit', 'dossiers en attente', 'nouvelles demandes'],
    group: 'Navigation',
    icon: CreditCard,
    iconBg: 'bg-status-success-bg text-status-success',
    type: 'navigation',
    moduleKey: 'credits',
    subModule: 'demandes',
    permission: { action: Actions.VIEW, subject: Subjects.CREDITS },
  },
  {
    id: 'nav-credits-enquetes',
    title: 'Crédits - Enquêtes',
    keywords: ['investigations', 'vérifications', 'enquête crédit'],
    group: 'Navigation',
    icon: CreditCard,
    iconBg: 'bg-status-success-bg text-status-success',
    type: 'navigation',
    moduleKey: 'credits',
    subModule: 'enquetes',
    permission: { action: Actions.VIEW, subject: Subjects.CREDITS },
  },
  {
    id: 'nav-credits-approbation',
    title: 'Crédits - Approbation',
    keywords: ['approuver crédit', 'validation crédit'],
    group: 'Navigation',
    icon: CreditCard,
    iconBg: 'bg-status-success-bg text-status-success',
    type: 'navigation',
    moduleKey: 'credits',
    subModule: 'approbation',
    permission: { action: Actions.APPROVE, subject: Subjects.CREDIT },
  },
  {
    id: 'nav-credits-echeancier',
    title: 'Crédits - Échéancier',
    keywords: ['échéances', 'calendrier', 'planning remboursement'],
    group: 'Navigation',
    icon: CreditCard,
    iconBg: 'bg-status-success-bg text-status-success',
    type: 'navigation',
    moduleKey: 'credits',
    subModule: 'echeancier',
    permission: { action: Actions.VIEW, subject: Subjects.CREDITS },
  },
  {
    id: 'nav-remboursements',
    title: 'Restitutions (Refus)',
    keywords: ['refund', 'restitution', 'remboursement frais engagement'],
    group: 'Navigation',
    icon: CreditCard,
    iconBg: 'bg-status-success-bg text-status-success',
    type: 'navigation',
    moduleKey: 'remboursements',
    permission: { action: Actions.VIEW, subject: Subjects.CREDITS },
  },
  {
    id: 'nav-comptes',
    title: 'Comptes',
    keywords: ['épargne', 'savings', 'comptes clients', 'compte courant', 'compte bloqué'],
    group: 'Navigation',
    icon: Wallet,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'comptes',
    permission: { action: Actions.VIEW, subject: Subjects.COMPTES },
  },
  {
    id: 'nav-tontines',
    title: 'Tontines',
    keywords: ['tontine', 'groupe épargne', 'ROSCA', 'cotisation'],
    group: 'Navigation',
    icon: DollarSign,
    iconBg: 'bg-status-warning-bg text-status-warning',
    type: 'navigation',
    moduleKey: 'tontines',
    permission: { action: Actions.VIEW, subject: Subjects.TONTINES },
  },

  // ─── Opérations ─────────────────────
  {
    id: 'nav-caisse',
    title: 'Caisse',
    keywords: ['caisse', 'guichet', 'cash', 'encaissement'],
    group: 'Navigation',
    icon: Landmark,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'caisse',
    permission: { action: Actions.VIEW, subject: Subjects.CAISSE },
  },
  {
    id: 'nav-caisse-operations',
    title: 'Caisse - Opérations',
    keywords: ['versement', 'retrait', 'transaction caisse'],
    group: 'Navigation',
    icon: Landmark,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'caisse',
    subModule: 'operations',
    permission: { action: Actions.VIEW, subject: Subjects.CAISSE },
  },
  {
    id: 'nav-caisse-historique',
    title: 'Caisse - Historique',
    keywords: ['journal caisse', 'transactions passées', 'historique'],
    group: 'Navigation',
    icon: Landmark,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'caisse',
    subModule: 'historique',
    permission: { action: Actions.VIEW, subject: Subjects.CAISSE },
  },
  {
    id: 'nav-caisse-transferts',
    title: 'Caisse - Transferts',
    keywords: ['coffre vers caisse', 'approvisionnement', 'transfert'],
    group: 'Navigation',
    icon: Landmark,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'caisse',
    subModule: 'transferts',
    permission: { action: Actions.VIEW, subject: Subjects.CAISSE },
  },
  {
    id: 'nav-caisse-mobilemoney',
    title: 'Caisse - Mobile Money',
    keywords: ['MTN', 'Airtel', 'MoMo', 'mobile money'],
    group: 'Navigation',
    icon: Landmark,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'caisse',
    subModule: 'mobilemoney',
    permission: { action: Actions.VIEW, subject: Subjects.CAISSE },
  },
  {
    id: 'nav-terrain',
    title: 'Gestion Agent',
    keywords: ['agents terrain', 'collecte', 'field', 'terrain', 'opérations'],
    group: 'Navigation',
    icon: MapPin,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'agentModules',
    permission: { action: Actions.VIEW, subject: Subjects.TERRAIN },
  },
  {
    id: 'nav-validations',
    title: 'Validations',
    keywords: ['approbation', 'validation en attente', 'approuver'],
    group: 'Navigation',
    icon: CheckCircle,
    iconBg: 'bg-status-success-bg text-status-success',
    type: 'navigation',
    moduleKey: 'validations',
    // No CASL permission, role-based (ADMIN, CHEF_AGENCE, SUPERVISEUR)
  },
  {
    id: 'nav-transferts',
    title: 'Transferts',
    keywords: ['virement', 'envoi argent', 'transfert'],
    group: 'Navigation',
    icon: ArrowLeftRight,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'transfert',
    permission: { action: Actions.VIEW, subject: Subjects.CLIENTS },
  },
  {
    id: 'nav-coffre',
    title: 'Coffre-Fort',
    keywords: ['coffre', 'safe', 'vault', 'trésor'],
    group: 'Navigation',
    icon: Lock,
    iconBg: 'bg-status-danger-bg text-status-danger',
    type: 'navigation',
    moduleKey: 'coffre',
    permission: { action: Actions.VIEW, subject: Subjects.COFFRE },
  },
  {
    id: 'nav-tresorerie',
    title: 'Trésorerie',
    keywords: ['trésorerie', 'encaisse', 'liquidité', 'treasury'],
    group: 'Navigation',
    icon: BarChart3,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'tresorerie',
    permission: { action: Actions.VIEW, subject: Subjects.CAISSE },
  },
  {
    id: 'nav-virements-programmes',
    title: 'Virements Programmés',
    keywords: ['virement auto', 'planifié', 'programmé'],
    group: 'Navigation',
    icon: ArrowLeftRight,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'virements_programmes',
  },

  // ─── Gestion ────────────────────────
  {
    id: 'nav-comptabilite',
    title: 'Comptabilité',
    keywords: ['compta', 'OHADA', 'GL', 'grand livre'],
    group: 'Navigation',
    icon: BookOpen,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'comptabilite',
    permission: { action: Actions.VIEW, subject: Subjects.COMPTABILITE },
  },
  {
    id: 'nav-comptabilite-journal',
    title: 'Comptabilité - Journal',
    keywords: ['journal comptable', 'écritures', 'entries'],
    group: 'Navigation',
    icon: BookOpen,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'comptabilite',
    subModule: 'journal',
    permission: { action: Actions.VIEW, subject: Subjects.COMPTABILITE },
  },
  {
    id: 'nav-comptabilite-grand-livre',
    title: 'Comptabilité - Grand Livre',
    keywords: ['general ledger', 'GL', 'grand livre'],
    group: 'Navigation',
    icon: BookOpen,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'comptabilite',
    subModule: 'grand-livre',
    permission: { action: Actions.VIEW, subject: Subjects.COMPTABILITE },
  },
  {
    id: 'nav-comptabilite-balance',
    title: 'Comptabilité - Balance',
    keywords: ['trial balance', 'balance générale'],
    group: 'Navigation',
    icon: BookOpen,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'comptabilite',
    subModule: 'balance',
    permission: { action: Actions.VIEW, subject: Subjects.COMPTABILITE },
  },
  {
    id: 'nav-rapports',
    title: 'Rapports',
    keywords: ['rapport', 'reporting', 'états', 'bilan'],
    group: 'Navigation',
    icon: BarChart3,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'rapports',
    permission: { action: Actions.VIEW, subject: Subjects.RAPPORTS },
  },
  {
    id: 'nav-rh',
    title: 'Personnel',
    keywords: ['RH', 'HR', 'employés', 'ressources humaines', 'staff'],
    group: 'Navigation',
    icon: UserCog,
    iconBg: 'bg-status-warning-bg text-status-warning',
    type: 'navigation',
    moduleKey: 'rh',
    permission: { action: Actions.VIEW, subject: Subjects.RH },
  },
  {
    id: 'nav-rh-employes',
    title: 'Personnel - Employés',
    keywords: ['liste employés', 'staff', 'effectifs'],
    group: 'Navigation',
    icon: UserCog,
    iconBg: 'bg-status-warning-bg text-status-warning',
    type: 'navigation',
    moduleKey: 'rh',
    subModule: 'list',
    permission: { action: Actions.VIEW, subject: Subjects.RH },
  },
  {
    id: 'nav-rh-conges',
    title: 'Personnel - Congés',
    keywords: ['leave', 'vacances', 'absence', 'congé'],
    group: 'Navigation',
    icon: UserCog,
    iconBg: 'bg-status-warning-bg text-status-warning',
    type: 'navigation',
    moduleKey: 'rh',
    subModule: 'conges',
    permission: { action: Actions.VIEW, subject: Subjects.CONGE },
  },
  {
    id: 'nav-rh-paie',
    title: 'Personnel - Paie',
    keywords: ['salaire', 'payroll', 'bulletin', 'paie'],
    group: 'Navigation',
    icon: UserCog,
    iconBg: 'bg-status-warning-bg text-status-warning',
    type: 'navigation',
    moduleKey: 'rh',
    subModule: 'paie',
    permission: { action: Actions.VIEW, subject: Subjects.PAIE },
  },

  // ─── Système ────────────────────────
  {
    id: 'nav-admin',
    title: 'Administration',
    keywords: ['admin', 'paramètres', 'settings', 'configuration'],
    group: 'Navigation',
    icon: Settings,
    iconBg: 'bg-surface-subtle text-content-secondary',
    type: 'navigation',
    moduleKey: 'administrateur',
    permission: { action: Actions.VIEW, subject: Subjects.ADMIN },
  },
  {
    id: 'nav-admin-users',
    title: 'Admin - Utilisateurs',
    keywords: ['users', 'comptes utilisateurs', 'gestion utilisateurs'],
    group: 'Navigation',
    icon: Shield,
    iconBg: 'bg-surface-subtle text-content-secondary',
    type: 'navigation',
    moduleKey: 'administrateur',
    subModule: 'users',
    permission: { action: Actions.MANAGE, subject: Subjects.USER },
  },
  {
    id: 'nav-admin-agences',
    title: 'Admin - Agences',
    keywords: ['branches', 'succursales', 'agences'],
    group: 'Navigation',
    icon: Building2,
    iconBg: 'bg-surface-subtle text-content-secondary',
    type: 'navigation',
    moduleKey: 'administrateur',
    subModule: 'agences',
    permission: { action: Actions.VIEW, subject: Subjects.AGENCE },
  },
  {
    id: 'nav-admin-roles',
    title: 'Admin - Rôles & Accès',
    keywords: ['permissions', 'RBAC', 'rôles', 'accès'],
    group: 'Navigation',
    icon: Shield,
    iconBg: 'bg-surface-subtle text-content-secondary',
    type: 'navigation',
    moduleKey: 'administrateur',
    subModule: 'roles',
    permission: { action: Actions.VIEW, subject: Subjects.RBAC },
  },
  {
    id: 'nav-admin-taux',
    title: 'Admin - Taux Produits',
    keywords: ['taux intérêt', 'plans crédit', 'produits financiers'],
    group: 'Navigation',
    icon: Settings,
    iconBg: 'bg-surface-subtle text-content-secondary',
    type: 'navigation',
    moduleKey: 'administrateur',
    subModule: 'product-rates',
    permission: { action: Actions.VIEW, subject: Subjects.ADMIN },
  },
  {
    id: 'nav-admin-branding',
    title: 'Admin - Branding',
    keywords: ['logo', 'thème', 'apparence', 'couleurs'],
    group: 'Navigation',
    icon: Palette,
    iconBg: 'bg-surface-subtle text-content-secondary',
    type: 'navigation',
    moduleKey: 'administrateur',
    subModule: 'branding',
    permission: { action: Actions.VIEW, subject: Subjects.ADMIN },
  },
  {
    id: 'nav-admin-devise',
    title: 'Admin - Devise',
    keywords: ['monnaie', 'currency', 'FCFA'],
    group: 'Navigation',
    icon: Coins,
    iconBg: 'bg-surface-subtle text-content-secondary',
    type: 'navigation',
    moduleKey: 'administrateur',
    subModule: 'currency',
    permission: { action: Actions.VIEW, subject: Subjects.ADMIN },
  },
  {
    id: 'nav-messages',
    title: 'Messages',
    keywords: ['chat', 'messagerie', 'conversations'],
    group: 'Navigation',
    icon: MessageSquare,
    iconBg: 'bg-status-info-bg text-status-info',
    type: 'navigation',
    moduleKey: 'messages',
  },
  {
    id: 'nav-profil',
    title: 'Mon Profil',
    keywords: ['profil', 'mon compte', 'mot de passe', 'paramètres perso'],
    group: 'Navigation',
    icon: User,
    iconBg: 'bg-accent/10 text-accent',
    type: 'navigation',
    moduleKey: 'profil',
  },
];

export const navigationProvider: SearchProvider = {
  id: 'navigation',
  label: 'Pages',
  icon: LayoutDashboard,
  iconBg: 'bg-accent/10 text-accent',
  priority: 1,
  mode: 'client',

  async search(query: string, ctx: SearchContext): Promise<SearchResult[]> {
    if (query.length < 1) return [];

    return NAVIGATION_ITEMS
      .map((item) => ({ ...item, score: scoreResult(query, item) }))
      .filter((item) => item.score > 0)
      .sort((a, b) => b.score - a.score);
  },
};
